networks:
  service-network:
    external: true
    name: service-network

services:
  video-service:
    shm_size: '20g'
    tmpfs:
      - /dev/shm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/imagine/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    build:
      context: .
    container_name: video-service
    expose:
      - "9002"
    devices:
      - /dev/dri:/dev/dri
    environment:
      - VALID_TOKEN=${VALID_TOKEN:-test-token}
      - DEFAULT_MODEL=${DEFAULT_MODEL:-cogvideox}
    volumes:
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
    networks:
      - service-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.video-service.rule=PathPrefix(`/imagine`)"
      - "traefik.http.routers.video-service.middlewares=chain-auth@file"
      - "traefik.http.services.video-service.loadbalancer.server.port=9002"
    restart: unless-stopped
