services:
  auth:
    build:
      context: ./auth
    container_name: video_auth
    environment:
      - VALID_TOKEN=${VALID_TOKEN:-test-token}
    networks:
      - video_net
    expose:
      - "9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/auth/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.video-auth.loadbalancer.server.port=9001"
      - "traefik.http.routers.video-auth.rule=PathPrefix(`/auth`)"
    restart: unless-stopped
    read_only: true
    security_opt:
      - no-new-privileges:true
    mem_limit: 256M
    mem_reservation: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  proxy:
    image: traefik:v3.2.1
    container_name: video_proxy
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:9000"
      - "--entrypoints.traefik.address=:8080"
      - "--api.dashboard=true"
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--providers.file.directory=/etc/traefik/dynamic"
    ports:
      - "9000:9000"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik/dynamic:ro
    networks:
      - video_net
    depends_on:
      auth:
        condition: service_healthy
    restart: unless-stopped
    mem_limit: 512M
    mem_reservation: 256M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  video_net:
    name: video_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
