networks:
  video_net:
    external: true
    name: video_network

services:
  video-service:
    shm_size: '20g'
    tmpfs:
      - /dev/shm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/imagine/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    build:
      context: .
    container_name: video_service
    expose:
      - "9002"
    devices:
      - /dev/dri:/dev/dri
    environment:
      - VALID_TOKEN=${VALID_TOKEN:-test-token}
      - DEFAULT_MODEL=${DEFAULT_MODEL:-cogvideox}
    volumes:
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
    networks:
      - video_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.video.rule=PathPrefix(`/imagine`)"
      - "traefik.http.routers.video.middlewares=chain-auth@file"
      - "traefik.http.services.video.loadbalancer.server.port=9002"
      - "traefik.http.routers.video.middlewares=strip-imagine@file,chain-auth@fi      - "traefik.http.routers.video.middlewares=strip-imagine@file,chain-auth@fi
    restart: unless-stopped
